#ifndef TIME_H
#define TIME_H

/* Timing constants (milliseconds) */
#define MILLIS_PER_SECOND 1000
#define MICROSECONDS_PER_MILLIS 1000
#define NANOSECONDS_PER_MILLIS 1000000L

#define PORT_RETRY_DELAY_MILLIS 8000
#define INIT_RETRY_DELAY_MILLIS 3000
#define MODEM_RESPONSE_DELAY_MILLIS 500

#define COMMAND_DELAY_MILLIS 100
#define SMS_SEND_DELAY_MILLIS 500
#define THREAD_SLEEP_MILLIS 5
#define STDIN_POLL_TIMEOUT_MILLIS 200

#endif